spring.application.name=banana-food
server.port=8080

# Configuracoes do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Encoding geral
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
